packages:
  - 'packages/*'
  - 'tenants/*'

catalogs:
  dependencies:
    nuxt: ^4.0.1
    class-variance-authority: ^0.7.1
    "@tailwindcss/vite": ^4.1.11
    lucide-vue-next: ^0.536.0
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.3.6
    vue: ^3.5.18
    vue-router: ^4.5.1
    clsx: ^2.1.1
    reka-ui: ^2.4.1
  
  devDependencies:
    autoprefixer: ^10.4.19
    postcss: ^8.4.31
    typescript: ~5.8.3
    "@vitejs/plugin-vue": ^5.0.4
    "@vue/tsconfig": ^0.7.0
    "@vitest/ui": ^2.1.8
    "@vitest/coverage-v8": ^2.1.8
    "@vue/test-utils": ^2.4.4
    "@testing-library/vue": ^8.0.2
    "@testing-library/jest-dom": ^6.4.2
    jsdom: ^25.0.1
    vite: ^5.4.12
    vitest: ^2.1.8
    vue-tsc: ^3.0.5
